### ISSUE TITLE
Not working on Thinkpad Yoga S1

### ISSUE THREAD

**Issue by michamos** [hadess/iio-sensor-proxy#10]
Hi,

I have a Thinkpad Yoga S1 running Debian Lenny, which contains the required patch to udev (I checked this explicitly).
I built the tag 0.1 of this project successfully (see #9 regarding master).
However, nothing happens when I turn the screen, see https://gist.github.com/michamos/faec99a0097dcb70bd85 for output of `iio-sensor-proxy` with debug messages. If I let it run, the last line just repeats.
Do you have any idea of what might be happening?

**Comment by hadess** [comment]
This is a driver bug. Make sure your kernel is as new as possible. See #6
