### ISSUE TITLE
XFCE support

### ISSUE THREAD

**Issue by well0nez** [hadess/iio-sensor-proxy#101]
Hey, i got everything working, expect that i dont use gnome.

is it possible to integrate / port this sensor-proxy to xfce?

thanks in advance

**Comment by hadess** [comment]
There's nothing GNOME specific implemented here, it's a D-Bus interface. The GNOME part is implemented in GNOME, just the same way that the XFCE part needs to be implemented in XFCE. Sorry, can't help here.
