### ISSUE TITLE
Asus TP200S no sensors found in distributions other that Ubuntu

### ISSUE THREAD

**Issue by modemaster** [hadess/iio-sensor-proxy#104]
Hi,

I installed the latest Ubuntu Desktop and found all IIO sensors.
When installing other distributions (Arch, Fedora) no sensors are found. I am on Fedora 24 Workstation now with latest updated system incl. kernel.

`[root@localhost ~]# G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy`
`** (process:7144): DEBUG: Could not find any supported sensors`

I prefer using Fedora. Any ideas?

Thanks a lot!

**Comment by hadess** [comment]
You need to contact Fedora about their kernel drivers, nothing we can do here.

**Comment by modemaster** [comment]
Okay thanks!
