### ISSUE TITLE
Help needed on ASUS UX310UA running Arch

### ISSUE THREAD

**Issue by Kaukov** [hadess/iio-sensor-proxy#106]
Hey there!

Today I tried installing `iio-sensor-proxy`, but I failed to do so from the repo, so I downloaded the package from the AUR. Everything looks fine, but I can't enable the `iio-sensor-proxy.service`, I can only start it. 

    The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
    settings in the [Install] section, and DefaultInstance for template units).
    This means they are not meant to be enabled using systemctl.
    Possible reasons for having this kind of units are:
    1) A unit may be statically enabled by being symlinked from another unit's
       .wants/ or .requires/ directory.
    2) A unit's purpose may be to act as a helper for some other unit which has
       a requirement dependency on it.
    3) A unit may be started when needed via activation (socket, path, timer,
       D-Bus, udev, scripted systemctl call, ...).
    4) In case of template units, the unit is meant to be enabled with some
       instance name specified.

I'm using Gnome 3.22 as a DE, but when I start the service, Gnome doesn't have the option for automatic brightness. Please help!

Also when I issue `monitor-sensor`, I get `Waiting for iio-sensor-proxy to appear` and it's stuck like that.

**Comment by hadess** [comment]
You're not supposed to start it by hand, it's started automatically when the sensor "appears". Reboot the machine and follow the instructions in the README. If iio-sensor-proxy isn't started, ask your distribution.

**Comment by Kaukov** [comment]
Thanks, I asked on the forums!
