### ISSUE TITLE
net.hadess.SensorProxy was not provided by any .service files

### ISSUE THREAD

**Issue by dinojr** [hadess/iio-sensor-proxy#107]
I'm running Gnome 3.22 in Ubuntu 16.10 on a Microsoft Surface Pro. The auto-rotate icon has disappeared from the Gnome User Menu since the last upgrade. I'm trying to debug the problem using the guidelines you provide:

> udevadm info --export-db

 gives several iio entries (see attached file) but 

> gdbus introspect --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy

fails with:

> Erreur : GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.hadess.SensorProxy was not provided by any .service files

I have iio-sensor-proxy 1.3-1 installed though.

Finally I tried to build from this repo but make failed with:

> fake-input-accelerometer.c: In function ‘send_uinput_event’:
  fake-input-accelerometer.c:90:2: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]  write (data->uinput, &ev, sizeof(ev));

What am I doing wrong ?

[udevadm-db.txt](https://github.com/hadess/iio-sensor-proxy/files/553361/udevadm-db.txt)

**Comment by hadess** [comment]
Looks likely that you didn't install it in the right place. Or `iio-sensor-proxy` could not detect those particular sensors.

Check the output of `systemctl status iio-sensor-proxy.service` and attach the output here.

**Comment by dinojr** [comment]
Actually I just noticed the service was simply not started: simply running
> sudo systemctl start iio-sensor-proxy.service
gets screen rotation working.

What's the proper way to have the service started at startup ?

**Comment by hadess** [comment]
It's started automatically through udev. You shouldn't need to do anything to get it started, other than maybe rebooting the machine.

**Comment by dinojr** [comment]
Turns out the iio-sensor-proxy package installs the file 80-iio-sensor-proxy.rules in /rules.d/, not /lib/udev/rules.d/. It looks as a bug to me, should I report it upstream ?

I added a link to this file in /lib/udev/rules.d/ and the service is now launched at startup. However it doesn't work: monitor-sensor reports that the orientation is not detected. If however I remove the link (so that udev doesn't start it) and if I run it with systemctl, it's working fine.

**Comment by hadess** [comment]
> Turns out the iio-sensor-proxy package installs the file 80-iio-sensor-proxy.rules in /rules.d/, not  lib/udev/rules.d/. It looks as a bug to me, should I report it upstream ?

You mean downstream I guess. You didn't have the udev development libraries installed when it was built, so `$PKG_CONFIG --variable=udevdir udev` was empty, hence the installation. I've fixed this now.

> I added a link to this file in /lib/udev/rules.d/ and the service is now launched at startup. However it doesn't work: monitor-sensor reports that the orientation is not detected. If however I remove the link (so that udev doesn't start it) and if I run it with systemctl, it's working fine.

See #82

**Comment by dinojr** [comment]
Thanks,
`Type=idle`
instead of
`Type=dbus`
seems to have fixed it
