### ISSUE TITLE
Lenovo ThinkPad Yoga 260

### ISSUE THREAD

**Issue by sdahdah** [hadess/iio-sensor-proxy#110]
It seems iio-sensor-proxy is not able to detect this device's sensors (light, accelerometer).

`monitor-sensor` displays: `Waiting for iio-sensor-proxy to appear` indefinitely.

Let me know what info you'd need and I can provide it.

**Comment by michauds** [comment]
The sensors won't be detected since the kernel isn't yet aware of them. Here's the article on the relevant patch: https://lkml.org/lkml/2016/5/31/3

FYI, the above mentioned patch is included in kernel 4.9. 

I'll ping back once I've had more time to test this out.

**Comment by zauguin** [comment]
I use a ThinkPad Yoga 460 (it uses the ISH too) with kernel 4.9. The light sensor works, but the accelerometer only works with `drv-iio-poll-accel.c` and not with `drv-iio-buffer-accel.c`.

I don't know anything about the iio subsystem, but if you need to test some code I'm happy to help.

**Comment by hadess** [comment]
> so a small patch was required.

What patch?

**Comment by zauguin** [comment]
zauguin@97e523f1edb227c4fd030a3bb205882d623f3579

**Comment by hadess** [comment]
This shouldn't be needed. Test with the current master please.

**Comment by zauguin** [comment]
You're right. It works with the current master. Awesome!

**Comment by hadess** [comment]
Great :)
