### ISSUE TITLE
Orientation is not returned to normal, if a laptop is in normal position again.

### ISSUE THREAD

**Issue by rolftheunissen** [hadess/iio-sensor-proxy#127]
On a HP 6560 the orientation/acceleration follows the keyboard orientation. If the laptop is tilted left/right/backwards, the screen rotates. However if the screen only returns to the normal orientation if the laptop is tilted forward, by the 35degrees threshold.

**Comment by hadess** [comment]
Sorry, I don't understand what you mean.

**Comment by miltmobley** [comment]
I think he means the display only reverses the rotation if the laptop base is tilted down so that it is toward him at an angle of 35 degrees from horizontal..

**Comment by hadess** [comment]
Moved to https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/issues/127
