### ISSUE TITLE
Yoga 900 example to couple with xrandr

### ISSUE THREAD

**Issue by mrquincle** [hadess/iio-sensor-proxy#129]
Hi all,

Although this might be obvious for you, Bastien, others might benefit from an example on how to couple it with xrandr. You can find such an example at https://github.com/mrquincle/yoga-900-auto-rotate/.

Summary:

- It uses gio/gio.h to read the device orientation from iio-sensor-proxy.
- It uses X11/extensions/Xrandr.h to set the default root window to the new orientation.
- It is by default a daemon, run with --verbose to see the output
- It has a super simple Makefile with just the required pkg-config configs.
- It doesn't complain property about lacking dependencies
- It has a systemd script that can run in user-space.
- It works, but you'll need to close and open the lid once.

Cheers,

Anne

**Comment by hadess** [comment]
I expect people who want to roll their own desktop integration, or use a desktop where this isn't implemented, to be able to search for that information.

Thanks for the notice though.
