### ISSUE TITLE
Lenovo Yoga 900 orientations off

### ISSUE THREAD

**Issue by khpylon** [hadess/iio-sensor-proxy#139]
An earlier version of iio-sensor-proxy worked fine, but in version 1.1 the axes are switched.  I installed version 2.0 but the same issue.  I created a udev hwdb file but it doesn't appear to be read, so I believe I'm not setting up the udev rules properly.

**Comment by hadess** [comment]
The hwdb entry is handled in systemd. Make sure to read the hwdb file mentioned in the `iio-sensor-proxy` README, which contains instructions on how to test changes.

You'll also need to make sure that the systemd version in your distribution is new enough. But that would be a question for your distribution to answer.
