### ISSUE TITLE
Can't find `configure`

### ISSUE THREAD

**Issue by ihincks** [hadess/iio-sensor-proxy#149]
Dumb question: where is the `configure` file that the installation instructions speak of? In reference to:

    ./configure --prefix=/usr --sysconfdir=/etc
    make
    make install

**Comment by hadess** [comment]
It's in the release tarball. You'd need to run `./autogen.sh` to compile from git.

**Comment by 842Mono** [comment]
what do I do after running `./autoghen.sh`? proceed with `make`?
