### ISSUE TITLE
Yoga 11e - Arch Linux

### ISSUE THREAD

**Issue by plimptm** [hadess/iio-sensor-proxy#154]
Thank you for writing the iio-sensor-proxy. I recently got a Yoga 11e (Windows 10 by default) and have installed Arch Linux with GNOME. Overall the system runs great, but I've yet to find any definitive answer as to whether or not the sensors have kernel support.

`Linux 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux`

I've compiled this code (from the AUR) and here's all I've ever gotten:

>`[root@ ~]# G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy`
>`** (process:5531): DEBUG: Could not find any supported sensors`

Booting the computer under Windows shows that the sensor devices are on a HID sensor hub. Here's some dmesg output that might be relevent:

>`[    2.479377] hidraw: raw HID events driver (C) Jiri Kosina`
>`[    7.526753] i2c_hid i2c-ITE8386:00: failed to reset device.`
>`[   13.713567] i2c_hid i2c-ITE8386:00: failed to reset device.`
>`[   19.900437] i2c_hid i2c-ITE8386:00: failed to reset device.`
>`[   26.086897] i2c_hid i2c-ITE8386:00: failed to reset device.`
>`[   27.100280] i2c_hid i2c-ITE8386:00: can't add hid device: -61`
>`[   27.117052] i2c_hid: probe of i2c-ITE8386:00 failed with error -61`
>`[   27.162428] hid-multitouch 0018:03EB:8C1F.0001: input,hidraw0: I2C HID v1.00 Device [ATML1000:00 03EB:8C1F] on i2c-ATML1000:00`

>`cat /sys/devices/platform/80860F41\:00/i2c-0/name`
>`Synopsys DesignWare I2C adapter`

Is this likely the same issue you discussed here: https://www.spinics.net/lists/linux-input/msg49080.html or a different issue? I'm hoping to help other Yoga 11e owners who might like to have the tablet features available.

**Comment by hadess** [comment]
It's not the same problem I'm afraid. Looks like a possible i2c controller driver problem.

**Comment by hadess** [comment]
Closing this as it's a kernel driver bug. If you still have problems when the i2c controller works correctly, please file a new issue.
