### ISSUE TITLE
ASUS UX330UA support on th way.

### ISSUE THREAD

**Issue by olerem** [hadess/iio-sensor-proxy#155]
Currently acpi_als can't read actual data on this laptop, acpi is providing only dummy values.
One ACPI bug is preventing it, i started to work on this issue.

**Comment by olerem** [comment]
Probably it should be documented here. I have seen it on at least 3 different ASUS models. ux32a, ux302, ux330ua - the DSDT code is almost identical: it provides a switch to enable real values or provdie some static dummy value.

**Comment by olerem** [comment]
patch is accepted for testing https://patchwork.kernel.org/patch/9704803/

**Comment by hadess** [comment]
Is this to report more laptops to be added to the tested list? We only add devices that were actually tested, not potentially supported devices.

**Comment by olerem** [comment]
It is tested, i own it and wrote the quirk :)
