### ISSUE TITLE
Quick question - Not working after restart. Not sure how to start it again.

### ISSUE THREAD

**Issue by alothings** [hadess/iio-sensor-proxy#157]
How do you start this after installation? Just systemctl start iio-sensor-proxy.service ?

I installed it 2 days ago and it was working. Today I switched to the Windows partition for a few hours, and when I logged back onto Manjaro, the screen does not rotate. 
It says iio-sensor-proxy service is running when I run systemctl, but it does not seem to be working. Any way to troubleshoot, or commands to send you the logs?

Thanks!

Edit: After testing changes I did to my system since I installed this, it seems that the Gnome extension "caffeine", was the one causing it to not start. (it was the only extension which when enabled it would stop iio-sensor-proxy to work).

**Comment by Houndie** [comment]
Not sure if this is your problem or not, but "systemctl start" just starts something the one time--you also want "systemctl enable iio-sensor-proxy.service" to have it autostart as part of the boot process.

**Comment by hadess** [comment]
Yes, there's nothing special about the `iio-sensor-proxy.service`, it's the same process as for any systemd service.
