### ISSUE TITLE
Acer Switch 12 no rotation

### ISSUE THREAD

**Issue by Laser-Cat** [hadess/iio-sensor-proxy#170]
I am using the Manjaro linux with 4.11 kernel.
I compiled installed iio-sensor-proxy from the master branch
Rotation is not working.
I guess the device it should monitor is iio:device3 instead of 0 or 4.....

I managed to make an ugly c++ script to get the rotation work by watching 
/sys/bus/iio/devices/iio:device3/in_rot_quaternion_raw and invoke xrandr when necessary

------------------------------------------------------------------------------------------
systemctl status iio-sensor-proxy gives

● iio-sensor-proxy.service - IIO Sensor Proxy service
   Loaded: loaded (/usr/lib/systemd/system/iio-sensor-proxy.service; static; ven
   Active: active (running) since Sat 2017-07-01 20:51:31 HKT; 2min 1s ago
 Main PID: 603 (iio-sensor-prox)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/iio-sensor-proxy.service
           └─603 /usr/sbin/iio-sensor-proxy

Jul 01 20:51:28 meow-secondary systemd[1]: Starting IIO Sensor Proxy service...
Jul 01 20:51:31 meow-secondary systemd[1]: Started IIO Sensor Proxy service.
Jul 01 20:51:31 meow-secondary iio-sensor-prox[603]: Failed to read float from /
Jul 01 20:51:31 meow-secondary iio-sensor-prox[603]: Failed to read float from /

After stopping the service 

sudo G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy produces
** (process:1949): DEBUG: Found IIO buffer ALS at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200041.7.auto/iio:device4
** (process:1949): DEBUG: Found device /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200041.7.auto/iio:device4 of type ambient light sensor at IIO Buffer Light sensor
** (process:1949): DEBUG: Found associated trigger at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/trigger0
** (process:1949): DEBUG: Found IIO buffer accelerometer at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0
** (process:1949): DEBUG: Found device /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0 of type accelerometer at IIO Buffer accelerometer
** (process:1949): DEBUG: Found IIO buffer compass at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2
** (process:1949): DEBUG: Found device /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2 of type compass at IIO Buffer Compass
** (process:1949): DEBUG: Found associated trigger at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/trigger0
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/scan_elements/in_accel_y_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/scan_elements/in_accel_x_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/scan_elements/in_timestamp_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/scan_elements/in_accel_z_en
** (process:1949): DEBUG: Got type for in_accel_y: is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Got type for in_accel_x: is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0

** (process:1949): WARNING **: Failed to read float from /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/in_scale

** (process:1949): WARNING **: Failed to read float from /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200073.2.auto/iio:device0/in_offset
** (process:1949): DEBUG: Got type for in_timestamp: is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:1949): DEBUG: Got type for in_accel_z: is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Built channel array for in_accel_x: index: 0, is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Built channel array for in_accel_y: index: 1, is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Built channel array for in_accel_z: index: 2, is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Built channel array for in_timestamp: index: 3, is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:1949): DEBUG: Found associated trigger at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200041.7.auto/trigger4
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200041.7.auto/iio:device4/scan_elements/in_illuminance_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200041.7.auto/iio:device4/scan_elements/in_intensity_both_en
** (process:1949): DEBUG: Got type for in_illuminance: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Got type for in_intensity_both: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_intensity_both: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_illuminance: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Found associated trigger at /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/trigger2
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2/scan_elements/in_magn_z_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2/scan_elements/in_magn_y_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2/scan_elements/in_rot_from_north_magnetic_tilt_comp_en
** (process:1949): DEBUG: Already enabled sensor /sys/devices/pci0000:00/INT3432:00/i2c-0/i2c-ITE8351:00/0018:048D:8380.0005/HID-SENSOR-200083.4.auto/iio:device2/scan_elements/in_magn_x_en
** (process:1949): DEBUG: Got type for in_magn_z: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Got type for in_magn_y: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Got type for in_rot_from_north_magnetic_tilt_comp: is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Got type for in_magn_x: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_magn_x: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_magn_y: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_magn_z: index: 2, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:1949): DEBUG: Built channel array for in_rot_from_north_magnetic_tilt_comp: index: 3, is signed: 1, bytes: 4, bits_used: 16, shift: 0, mask: 0x65535, be: 0
** (process:1949): DEBUG: Handling driver refcounting method 'ClaimLight' for ambient light sensor device
** (process:1949): DEBUG: Handling driver refcounting method 'ClaimAccelerometer' for accelerometer device
** (process:1949): DEBUG: process_scan_1: channel_index: 0, chan_name: in_intensity_both, channel_data_index: 0 location: 0
** (process:1949): DEBUG: Light read from IIO on 'iio:device4': 0 (scale 0.010000) = 0.000000
** (process:1949): DEBUG: Light level sent by driver (quirk applied): 0.000000 (unit: lux)
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'
** (process:1949): DEBUG: No new data available on 'iio:device4'
** (process:1949): DEBUG: No new data available on 'iio:device0'

**Comment by hadess** [comment]
From https://github.com/hadess/iio-sensor-proxy/blob/master/README.md#known-problems:

> Every Linux kernel from 4.3 up to version 4.12 had a bug that made
> made iio-sensor-proxy fail to see any events coming from sensors until the 
> sensor was power-cycled (unplugged and replugged, or suspended and resumed).
> 
> The bug was finally fixed in [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?h=fixes-togreg&id=eafad73ed3851707fa6e3124a255fc049ff9545d)
> in the upstream kernel and backported to stable releases. If you experience
> unresponsive sensors, ask your distributor to make sure this patch was 
> applied to the version you're using.

Please reopen if you still have problems with a kernel containing this fix.
