### ISSUE TITLE
Orientation Inverted 

### ISSUE THREAD

**Issue by shiman6** [hadess/iio-sensor-proxy#178]
I've been trying to figure this out for a while and I've likely narrowed it down to 60-sensor.hwdb. However, attempting to write my own quirk seems to do nothing. I cannot find out the accel_mount_matrix of the specific device I have, and i'm not even sure if i've formatted the sensor string correctly.
Here's the udevadm info --export-db output cut to just the iio sensors.

`P: /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-5/i2c-NPCE0388:00/0018:0416:C300.0001/HID-SENSOR-200073.1.auto/iio:device0`
`N: iio:device0`
`E: DEVNAME=/dev/iio:device0`
`E: DEVPATH=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-5/i2c-NPCE0388:00/0018:0416:C300.0001/HID-SENSOR-200073.1.auto/iio:device0`
`E: DEVTYPE=iio_device`
`E: IIO_SENSOR_PROXY_TYPE=iio-buffer-accel`
`E: MAJOR=243`
`E: MINOR=0`
`E: SUBSYSTEM=iio`
`E: SYSTEMD_WANTS=iio-sensor-proxy.service`
`E: TAGS=:systemd:`
`E: USEC_INITIALIZED=1623164`

`P: /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-5/i2c-NPCE0388:00/0018:0416:C300.0001/HID-SENSOR-200073.1.auto/trigger0`
`E: DEVPATH=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-5/i2c-NPCE0388:00/0018:0416:C300.0001/HID-SENSOR-200073.1.auto/trigger0`
`E: SUBSYSTEM=iio`

And here's my attempted quirk

`#########################################`
`# IdeaPad Flex I2C`
`#########################################`
`sensor:modalias:acpi:platform:*NPCE0388*:dmi:*`
 `ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, -1, 0; 0, 0, -1`

Also, not sure how to add the "help wanted" tag as this is probably not an issue with iio-sensor-proxy

**Comment by hadess** [comment]
Quirks live in systemd, please read the documentation at the top of the systemd files for those quirks, and use the other quirks as example. Once you've done this, please file an issue against systemd itself.
