### ISSUE TITLE
sensitivity on yoga 2 pro

### ISSUE THREAD

**Issue by johnpaul5** [hadess/iio-sensor-proxy#18]
It works correctly on my yoga 2 pro, but sometimes changes the orientation while not rotating the screen. Is there any way to adjust the accelerometer sensitivity (assuming this is the cause) ?

**Comment by hadess** [comment]
No, and we don't plan on adding any configuration for this. We might be using the wrong sensor for this though, maybe the gyroscope is better suited.

**Comment by johnpaul5** [comment]
Ok thanks anyway for your work on this program, I'll follow future updates.
