### ISSUE TITLE
autogen.sh: configure: error: Package requirements (gio-2.0 gudev-1.0 >= 232)

### ISSUE THREAD

**Issue by 842Mono** [hadess/iio-sensor-proxy#187]
When I run autogen.sh I get this:

    configure: error: Package requirements (gio-2.0 gudev-1.0 >= 232) were not met:

    Requested 'gudev-1.0 >= 232' but version of gudev-1.0 is 230

I can't find the packages anywhere, how can I install them

**Comment by draosh** [comment]
I would like to know it too. only libgudev  231+1+g0841288-1 in repo.

**Comment by jbicha** [comment]
Ask your distro or compile from source:

https://download.gnome.org/sources/libgudev/

**Comment by draosh** [comment]
Thanks! Now it's clear. I see it in "testing" arch repo. Not sure I should replace the installed one with it.
