### ISSUE TITLE
On login or wake from suspend, display rotates clockwise.

### ISSUE THREAD

**Issue by dnulho** [hadess/iio-sensor-proxy#198]
Every time I log in or wake my HP Pavilion up from suspend, my display rotates to the right 90*.

This started occurring after upgrading to the newest Ubuntu 17.10 release.

You can see the troubleshooting I have done so far at:
https://bugs.launchpad.net/ubuntu/+source/iio-sensor-proxy/+bug/1726160

**Comment by hadess** [comment]
There's no version number for iio-sensor-proxy, or debug log as mentioned in the README. I'm going to assume that it's a combination of the HP accelerometer driver (`lis3lv02d`), and the lack of quirk in systemd which causes this problem. See https://github.com/systemd/systemd/issues/7151
