### ISSUE TITLE
Lenovo Yoga 910 - AmbientLight and Accelerometer not working

### ISSUE THREAD

**Issue by henrythor** [hadess/iio-sensor-proxy#200]
Here's debug output from running iio-sensor-proxy.service from boot https://pastebin.com/GUQ9PAGN

Kernel version: 4.13.12-1-ARCH
iio-sensor-proxy version: 2.4-3

Seems there's some hardware quirk that's preventing iio-sensor-proxy from reading data from these sensors.

Any suggestions?

**Comment by henrythor** [comment]
Accelerometer is working now but only after a sleep and wake-up. The ambient light sensor isn't outputting anything.

**Comment by hadess** [comment]
Check the README for the exact versions that are broken. Bear in mind that it's broken again since an unknown version:
https://www.spinics.net/lists/linux-iio/msg36003.html

**Comment by RussianNeuroMancer** [comment]
Do you still have this issue with latest kernel and iio-sensor-proxy?

**Comment by hadess** [comment]
I'm going to assume this works correctly now. Please reopen if not.
