### ISSUE TITLE
bash: ./configure: No such file or directory error 

### ISSUE THREAD

**Issue by gideion** [hadess/iio-sensor-proxy#209]
When attempting  ~/Git/iio-sensor-proxy$ ./configure --prefix=/usr --sysconfdir=/etc
I get the error 
bash: ./configure: No such file or directory

Running Ubuntu 16.04

thx

**Comment by hadess** [comment]
Use your distribution's packages, or use tarballs to  build iio-sensor-proxy.
Duplicate of #149
