### ISSUE TITLE
How does one go about adding support for new sensors? 2017 Spectre x360 13 - i7 8550u

### ISSUE THREAD

**Issue by ilikenwf** [hadess/iio-sensor-proxy#211]
I can get udev output but it seems the sensors aren't yet supported.
Does this involve kernel patching, iio-sensor-proxy patching, or both?

**Comment by hadess** [comment]
Unless it's a new _type_ of sensor, only making sure the kernel supports it should be needed. We support drivers written for the IIO, input or hwmon classes of drivers, depending on the type of sensor as well.

**Comment by hadess** [comment]
I looked at the original udevadm listing, and it could be that your kernel doesn't have the `hid-sensor-hub` driver available. Might be a good idea to try with a more featureful distro's kernel, such as an Ubuntu or Fedora live CD.

If it still fails, please get in touch with the linux-iio mailing-list, they might be able to help you out.
