### ISSUE TITLE
[Feature] Support extra sensors

### ISSUE THREAD

**Issue by Depau** [hadess/iio-sensor-proxy#221]
I just noticed that my computer (Lenovo ThinkPad X1 Yoga 1st) has also a rotation and magnetic field sensor:

```shell
$ cat /sys/bus/iio/devices/iio:*/name
gyro_3d
magn_3d
gyro_3d
accel_3d
als
```

It would be nice if IIO sensor proxy supported them too, so that new apps can be developed on top of it (I would easily make a compass app just for fun).

**Comment by hadess** [comment]
Compasses are already supported through Geoclue. There's no direct access to the compass.

For what it's worth:
> gyro_3d

A gyro which we don't need (or would use in combination with the accelerometer)

> magn_3d

Already used by Geoclue

> gyro_3d

Another gyro.

> accel_3d

The accelerometer.

> als

Light sensors, which are also already supported.

**Comment by Depau** [comment]
Thank you.
May I ask why you're not going to support gyro? I like the current dbus API for the other sensors.
Is this project strictly aiming at what may be useful for a desktop environment?

**Comment by hadess** [comment]
> May I ask why you're not going to support gyro?

Why do you want to use it? If it's something we're interested in, we'll probably accept patches for it.

> I like the current dbus API for the other sensors.
> Is this project strictly aiming at what may be useful for a desktop environment?

Depends on what you want to use it for.
