### ISSUE TITLE
After upgrade to Linux 4.17rc1 it's required to suspend/resume to get accelerometer and ambient light sensor working

### ISSUE THREAD

**Issue by RussianNeuroMancer** [hadess/iio-sensor-proxy#224]
Accelerometer and ambient light sensor works only after suspend/resume on Lenovo Miix2 (INV6050 sensor; iio-sensor-proxy version is 2.4) after upgrade from Linux 4.16 to Linux 4.17rc1. Both sensors is detected after boot but undefined:

```
~$ monitor-sensor
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: undefined)
=== Has ambient light sensor (value: 0.000000, unit: lux)
```
After suspend/resume both sensors start working normally.

There is no such issue with Linux 4.16.0.

**Comment by hadess** [comment]
It's a kernel issue, nothing I can do about it.

**Comment by MCSH** [comment]
I'm not sure if it's the same problem but after suspend/resume when it rotates, the screen goes blank and only the cursor is visible

**Comment by RussianNeuroMancer** [comment]
@hadess 

> It's a kernel issue, nothing I can do about it.

Ok, I'll recheck with 4.17 and fill to kernel bugtracker.

@MCSH 

> the screen goes blank and only the cursor is visible

Your issue is either combination of two (this one and some other in video driver, compositor, something else) or completely different.
