### ISSUE TITLE
Accelerometer orientation problem.

### ISSUE THREAD

**Issue by Tuxman2** [hadess/iio-sensor-proxy#230]
Hello, 

I saw there is a solution to solve the accelerometer orientation problem on some devices. The solution is this file: https://github.com/systemd/systemd/blob/master/hwdb/60-sensor.hwdb

I would like to add my hardware to this file but I don't know how to recover all the information from my hardware. 

Can you help me ?

Thanks.

**Comment by hadess** [comment]
The file itself is as well documented as can be in the limited amount of space available.
In particular, this explains the format of the string:
https://github.com/systemd/systemd/blob/master/hwdb/60-sensor.hwdb#L12

Alternatively, this explains how to create a new issue against systemd's hwdb:
https://github.com/systemd/systemd/blob/master/hwdb/60-sensor.hwdb#L24
