### ISSUE TITLE
thinkpad x220 tablet could not find any supported sensors

### ISSUE THREAD

**Issue by 99ninetynine** [hadess/iio-sensor-proxy#241]
similar problem https://github.com/hadess/iio-sensor-proxy/issues/236
kernel v4.19-rc4 not fixed too
auto screen rotation works only on windows

**Comment by hadess** [comment]
I cannot make drivers appear, sorry. Check with your distribution why the driver for this device is disabled.

**Comment by 99ninetynine** [comment]
> I cannot make drivers appear, sorry. Check with your distribution why the driver for this device is disabled.

Sorry for quickly issue, im trying out gentoo and added option into kernel
Device Drivers
* Industrial IO -> (enable the generic IIO drivers in the sections for accelerometers and light sensors)
