### ISSUE TITLE
Device orientation is not correct on my device

### ISSUE THREAD

**Issue by BruceZhang1993** [hadess/iio-sensor-proxy#249]
Device: Lenovo IdeaPad MIIX 510-12ISK (2-in-1 Tablet)
OS: Arch Linux Latest Stable
Kernel: 4.19.4
iio-sensor-proxy version: 2.5 in community

monitor-sensor result:

```
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: left-up)
=== No ambient light sensor
    Accelerometer orientation changed: normal
    Accelerometer orientation changed: left-up
```

Issue description: When my device orientation is normal; it returns left-up. When left-up, returns normal.

**Comment by hadess** [comment]
You'll need to supply a quirk to systemd. See https://github.com/hadess/iio-sensor-proxy#accelerometer-orientation
