### ISSUE TITLE
teclast f5 tablet could not find any supported sensors

### ISSUE THREAD

**Issue by luluprat** [hadess/iio-sensor-proxy#250]
Hello,
i have the same error:
 could not find any supported sensors
and the service doesn't start
any help ?

**Comment by hadess** [comment]
It means that you, or the person compiling the kernel you're using, probably didn't enable the drivers necessary for it, or there is no driver available for it.

Please contact your distribution about it.

**Comment by hadess** [comment]
Looks like it could be a KIOX010A accelerometer, enabled though the `CONFIG_KXCJK1013` configuration option:
https://github.com/systemd/systemd/pull/11005/commits
