### ISSUE TITLE
How can I buid this driver?

### ISSUE THREAD

**Issue by Butylochnik** [hadess/iio-sensor-proxy#251]
I can't build this driver. I see the following error:
If I follow instruction I see:
butylochnik@butylochnik-ImPad-W1001-v2:~/Documents/Work/ImPad/Accel$ ./configure --prefix=/usr --sysconfdir=/etc
bash: ./configure: No such file or directory

If i try to run autogen.sh I see:
butylochnik@butylochnik-ImPad-W1001-v2:~/Documents/Work/ImPad/Accel$ bash ./autogen.sh 
./autogen.sh: line 16: autoconf: command not found
*** WARNING: I am going to run 'configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** './autogen.sh' command line.

./autogen.sh: line 25: aclocal: command not found

**Comment by hadess** [comment]
Either install it from your distribution, run `autogen.sh` before running `configure`, or run `configure` from the generated releases (in the release tab).

I'll let you figure out how to install the missing programs.
