### ISSUE TITLE
Work on Teclast X98 Pro

### ISSUE THREAD

**Issue by andrew-terekhov** [hadess/iio-sensor-proxy#257]
Hello!
Successfully run on Teclast X98 Pro.

Please add device settings to 60-sensor.hwdb

sensor:modalias:acpi:BMA250E*:dmi:*:svnTECLAST:pnX98Pro:*
 ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 1

**Comment by hadess** [comment]
This file lives in [systemd](https://github.com/systemd/systemd), so nothing we can fix here. Thanks for the report.
