### ISSUE TITLE
Kernel bug (?) - i915 can't find GPIO device

### ISSUE THREAD

**Issue by HoshiYamazaki** [hadess/iio-sensor-proxy#264]
https://pastebin.com/2vAe5ZxY

```
[    6.396125] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    6.396503] i915 0000:00:02.0: cannot find GPIO chip gpio_crystalcove, deferring
```

I know that the issue is not directly releated to the project, but maybe somebody knows how to fix that?

**Comment by hadess** [comment]
This isn't a forum, try your distribution's mailing-list or the linux kernel lists.
