### ISSUE TITLE
Accelerometer orientation under Wayland and under xorg.

### ISSUE THREAD

**Issue by Tuxman2** [hadess/iio-sensor-proxy#265]
Hi,

There is one thing I would like to understand.

I tested the accelerometer orientation under Wayland and under xorg. Under Wayland, it is instantaneous (the display appears at once) when I tilt the screen, in the other hand, under xorg it is not the case. The display is black during a few seconds and then the screen appears only. Why under xorg it is not instantaneous as under Wayland when the screen is tilt ? 
That's I would like to understand.

Thanks.

**Comment by hadess** [comment]
The differences between Wayland and Xorg are irrelevant to iio-sensor-proxy which doesn't run inside a graphical session, as explained in the README.
