### ISSUE TITLE
Lenovo Yoga 11-ISK accelerometer orientation changes constantly

### ISSUE THREAD

**Issue by selankon** [hadess/iio-sensor-proxy#266]
Hi

I have a Lenovo Yoga 11-ISK  with a linux mint 19.1. If I execute `monitor-sensor` I get an orientation change constantly, here a sample output:

```
    Accelerometer orientation changed: left-up
    Accelerometer orientation changed: normal
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: left-up
    Accelerometer orientation changed: right-up
    Accelerometer orientation changed: normal
    Accelerometer orientation changed: right-up
```
I can't find information about how to calibrate it or what is the cause of the problem. Any ideas?

**Comment by hadess** [comment]
Please test with version 2.6.

**Comment by hadess** [comment]
Moved to https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/issues/266
