### ISSUE TITLE
Orientation reported wrong for Mediacom Flexbook Edge

### ISSUE THREAD

**Issue by naked-head** [hadess/iio-sensor-proxy#267]
Hi there,
with flexbook edge 11 and ubuntu 19.04 I get wrong orientation so I had to disable iio-sensor-proxy and restart the session.

probably i need to add a new setting to 60-sensor.hwdb but I don't know how and obviously I don't know what....

thanks

**Comment by hadess** [comment]
> probably i need to add a new setting to 60-sensor.hwdb but I don't know how and obviously I don't know what....

For the how, documentation is linked in the README, for the what, there are plenty of examples in systemd itself. I'm afraid I can't help you figure this out, it would just be too time consuming for me.
