### ISSUE TITLE
Add support for HP EliteBook 820 G1

### ISSUE THREAD

**Issue by jtsagata** [hadess/iio-sensor-proxy#281]
HP EliteBook 820 G1 returns wrong rotations

A fix is
```
sensor:modalias:platform:lis3lv02d:dmi:*svn*Hewlett-Packard*:*
  ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1
```

But for some reason i can't get a more specific rule

**Comment by hadess** [comment]
This would be a fix for systemd, not for iio-sensor-proxy, as mentioned in the README:
https://github.com/hadess/iio-sensor-proxy#accelerometer-orientation
