### ISSUE TITLE
Dell Venue 8 Pro Accelerometer Fix

### ISSUE THREAD

**Issue by jc11686** [hadess/iio-sensor-proxy#289]
The Dell Venue 8 Pro (3845) requires these settings for the accelerometer to be correct. The rotation was always off 90 degrees. This fixed it for me:

```
# DELL VENUE 8 PRO 3845
sensor:modalias:acpi:INVN6500*:dmi:*svnDell*:pnVenue8Pro3845*
 ACCEL_MOUNT_MATRIX=0, -1, 1; -1, 0, 0; 0, 0, 1
```

**Comment by hadess** [comment]
Those go to systemd, usually as a pull request. That's the file to modify:
https://github.com/systemd/systemd/blob/master/hwdb.d/60-sensor.hwdb
