### ISSUE TITLE
Limit access to heading to Geoclue

### ISSUE THREAD

**Issue by hadess** [hadess/iio-sensor-proxy#29]
It's not directly useful to applications, as it's exporting the magnetic North heading, not the True North heading. Geoclue will usually have enough information to convert it.

**Comment by volkov0aa** [comment]
I want to write the plugin for Qt Sensors and QCompassReading documentation states: "The compass returns the azimuth of the device as degrees from magnetic north". So it can be useful in Qt applications.

**Comment by hadess** [comment]
Qt Sensors and QCompassReading should access it through Geoclue, not directly.

**Comment by volkov0aa** [comment]
Will geoclue provide the magnetic North heading?

**Comment by hadess** [comment]
Ask Geoclue :)

**Comment by volkov0aa** [comment]
I just realized that Geoclue provides the direction in which a device is moving, but not the direction in which a device is pointing.

**Comment by hadess** [comment]
There's a geoclue mailing-list...
