### ISSUE TITLE
AmbientLight on v975w

### ISSUE THREAD

**Issue by dynek** [hadess/iio-sensor-proxy#53]
Hello,

Thank you for your work!

AmbientLight doesn't work on v975w, right ?
"readonly b HasAmbientLight" says "false" when querying gdbus.

Cheers

**Comment by hadess** [comment]
There's no ambient light sensor in that tablet. Feel free to reopen if you manage to find any proofs to the contrary.

**Comment by dynek** [comment]
You are definitely right - Do not know where I thought the device had such sensor :-/
