### ISSUE TITLE
gdm errors - not authorized

### ISSUE THREAD

**Issue by f3flight** [hadess/iio-sensor-proxy#63]
Today I have downloaded, compiled and installed the iio-sensor-proxy service.
It works okay, but what is strange is that every time the light changes (light sensor value), I get the following error messages in log:

```
Dec 13 21:41:09 universe pkexec[2887]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm] [COMMAND=/usr/lib/gnome-settings-daemon/gsd-backlight-helper --set-brightness 927]
Dec 13 21:41:09 universe gnome-session[366]: Error executing command as another user: Not authorized
Dec 13 21:41:09 universe gnome-session[366]: This incident has been reported.
```

The value of --set-brightness is always the same - 927. If I enable automatic brightness in Power settings then next to these messages I see:

```
Dec 13 21:39:58 universe pkexec[2824]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Dec 13 21:39:58 universe pkexec[2824]: user: Executing command [USER=root] [TTY=unknown] [CWD=/home/user] [COMMAND=/usr/lib/gnome-settings-daemon/gsd-backlight-helper --set-brightness 477]
```

Which looks ok and the value here changes, and the brightness changes accordingly. But if I disable automatic brightness the first example still keeps popping in log (each time the light sensor value changes).

Any ideas what is going wrong here, why there is a strange attempt to change brightness to 927? I use Arch Linux, kernel is 3.2.5, gdm & gnome.

**Comment by f3flight** [comment]
filed a bug in gnome just in case - https://bugzilla.gnome.org/show_bug.cgi?id=759414

**Comment by hadess** [comment]
Upstream bug was fixed.
