### ISSUE TITLE
Does not come back after sleep/wake up

### ISSUE THREAD

**Issue by Cygn** [hadess/iio-sensor-proxy#7]
This works handsomely on TP Yoga S1 (0483:91d1) on 3.18.3 (F21) but only until the first sleep.  
Restarting the service apparently isn't enough to make it work again; only a restart would do. Probably a rmmod/moprobe cycle is necessary, but I was unable to find out which modules and in what order.

**Comment by hadess** [comment]
Report this to the linux-iio mailing-list, the drivers are broken.
