### ISSUE TITLE
Asus-Transformer-Book-Flip-TP300LD

### ISSUE THREAD

**Issue by cgfaas** [hadess/iio-sensor-proxy#80]
// Hi,

// My name is Craig Faas craig@inventor.ninja

// I am working on an Asus-Transformer-Book-Flip-TP300LD Ultrobook Touchscreen Computer
// and trying to get the orientation sensor running to rotate the screen
// and shut off the usb keyboard
// I came across your iio-sensor-proxy - April 25, 2016 on github and through D-Bus
// Thank you.

// output of `udevadm info --export-db`

P: /devices/platform/asus-nb-wmi/hwmon/hwmon1
E: DEVPATH=/devices/platform/asus-nb-wmi/hwmon/hwmon1
E: SUBSYSTEM=hwmon
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=19170306

P: /devices/platform/coretemp.0/hwmon/hwmon2
E: DEVPATH=/devices/platform/coretemp.0/hwmon/hwmon2
E: SUBSYSTEM=hwmon
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=19229476

P: /devices/virtual/hwmon/hwmon0
E: DEVPATH=/devices/virtual/hwmon/hwmon0
E: SUBSYSTEM=hwmon
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=17627133

// output of `gdbus introspect --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy`
node /net/hadess/SensorProxy {
  interface org.freedesktop.DBus.Properties {
    methods:
      Get(in  s interface_name,
          in  s property_name,
          out v value);
      GetAll(in  s interface_name,
             out a{sv} properties);
      Set(in  s interface_name,
          in  s property_name,
          in  v value);
    signals:
      PropertiesChanged(s interface_name,
                        a{sv} changed_properties,
                        as invalidated_properties);
    properties:
  };
  interface org.freedesktop.DBus.Introspectable {
    methods:
      Introspect(out s xml_data);
    signals:
properties:
  };
  interface org.freedesktop.DBus.Peer {
    methods:
      Ping();
      GetMachineId(out s machine_uuid);
    signals:
    properties:
  };
  interface net.hadess.SensorProxy {
    methods:
      ClaimAccelerometer();
      ReleaseAccelerometer();
      ClaimLight();
      ReleaseLight();
    signals:
    properties:
      readonly b HasAccelerometer = false;
      readonly s AccelerometerOrientation = 'undefined';
      readonly b HasAmbientLight = true;
      readonly s LightLevelUnit = 'lux';
      readonly d LightLevel = 138.0;
  };
  node Compass {
  };
};

\\ The Light Sensor works. The orientation sensor is undefined..
\\  output of `G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy`

** (process:24621): DEBUG: Found IIO poll light at /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0008:00/iio:device0
** (process:24621): DEBUG: Found device /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0008:00/iio:device0 of type ambient light sensor at IIO Polling Light sensor
** (process:24621): DEBUG: Handling driver refcounting method 'ClaimLight' for ambient light sensor device
** (process:24621): DEBUG: Handling driver refcounting method 'ClaimLight' for ambient light sensor device
** (process:24621): DEBUG: Handling driver refcounting method 'ClaimAccelerometer' for accelerometer device
** (process:24621): DEBUG: Handling driver refcounting method 'ClaimAccelerometer' for accelerometer device
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 149.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 0.000000 to 149.000000
* (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 149.000000 to 148.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 151.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 148.000000 to 151.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 151.000000 to 150.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 154.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 150.000000 to 154.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 152.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 154.000000 to 152.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 152.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 152.000000 to 148.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 148.000000 to 150.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 146.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 150.000000 to 146.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 149.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 149.000000 to 145.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 147.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 145.000000 to 147.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 147.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 152.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 147.000000 to 152.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 157.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 152.000000 to 157.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 147.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 157.000000 to 147.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 147.000000 to 148.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 148.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 148.000000 to 150.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 150.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 152.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 150.000000 to 152.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 152.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 146.000000 (unit: lux)
** (process:24621): DEBUG: Emitted light changed: from 152.000000 to 146.000000
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 146.000000 (unit: lux)
** (process:24621): DEBUG: Light level sent by driver (quirk applied): 151.000000 (unit: lux)

// If a light is shown to the camera the 'virtual' sensor lux reading goes way up (3000's)

// END

**Comment by hadess** [comment]
> readonly b HasAccelerometer = false;

Your machine doesn't have an accelerometer, or you didn't build the driver for that accelerometer. You'll need to figure out what driver is missing though.
