### ISSUE TITLE
Tested on Yoga 2 11''

### ISSUE THREAD

**Issue by davidcortesortuno** [hadess/iio-sensor-proxy#81]
Hi, I'm using Arch with kernel 4.5.1 and Gnome 3.20 in a Yoga 2 11 inch laptop. Screen rotation and ambient light sensor are working perfectly :)

Is it possible to lock the touchpad or keyboard when the screen rotates? Or is this only  done manually?

**Comment by hadess** [comment]
> Is it possible to lock the touchpad or keyboard when the screen rotates? Or is this only done manually?

It should be done in the desktop environment, if the firmware doesn't handle it automatically. Ideally, the Lenovo Yogas would only allow orientation changes when in tablet mode, not when opened up...

I've added that model to the README though, thanks.
