### ISSUE TITLE
Toshiba Radius 11 L10WC10C

### ISSUE THREAD

**Issue by gevasiliou** [hadess/iio-sensor-proxy#89]
Hello,
I would like to confirm that in a fresh Ubuntu 16.04 with Gnome 3.18 installation, this code is installed by Ubuntu iso automatically as a default package and screen rotation works just perfect out of the box with Gnome 3.18 in my Toshiba Radius 11 L10WC10C eequipped with ITE 8350 accelerometer.

So if you like, you can add this laptop model in your "Tested On" section. 

PS1: By the way, for those who may wonder, on Ubuntu 16.04 with Unity, this sensor-proxy package can be manually installed without problems, monitor-sensor will give you correct messages about accelerometer and screen orientation (normal, left is up, bottom is up, etc), BUT Unity seems that is not capable to make advantage of this sensor-proxy code and does not autorotate the screen when you fold / turn your screen.

**Comment by hadess** [comment]
I've added your device to the README.

I'm afraid that I can't help with Unity not picking up orientation changes though, you'll need to report that against Unity itself. Recent versions of Ubuntu GNOME should work though.
