### ISSUE TITLE
iio-poll-accel driver hardcoded device name

### ISSUE THREAD

**Issue by Icenowy** [hadess/iio-sensor-proxy#91]
It supports only iio devices named "i2c-SMO8500:00".
But now I have an Allwinner tablet with a mma8653 polling accelerometer. It's configured at the device tree, and will have the name "mma8653" given by the driver.

I did an ugly hack on it ( replace "i2c-SMO8500:00" to "mma8653" in iio_poll_accel_discover() ), now iio-sensor-proxy works (although orientation is 90 degrees off)

**Comment by hadess** [comment]
Ideally, the ->discover in `drv-iio-poll-accel.c` would use the capabilities (eg. the files in the sysfs directory) of the device instead of hard-coded names to figure out whether an accelerometer is supported. Want to look into it?

**Comment by hadess** [comment]
See also #59

**Comment by hadess** [comment]
This is actually a duplicate of #39

**Comment by hadess** [comment]
(which is now fixed in master)
