### ISSUE TITLE
Wrong orientation in landscape mode on Asus Transformer Book TP500LB

### ISSUE THREAD

**Issue by M0Rf30** [hadess/iio-sensor-proxy#92]
Hi,
I've tested this piece of software on an asus tp500lb
Accelerometer is correctly detected, but on service start the screen is oriented in the wrong way.
In landscape the screen is inverted. Module is a kionix kxcjk-1013

**Comment by hadess** [comment]
Does the orientation change between grub and the graphical bootloader?

**Comment by M0Rf30** [comment]
No, Efi grub is loaded correctly with no graphical issues.

**Comment by M0Rf30** [comment]
no, the linux graphical boot is not inverted. however in landscape  mode sensor-monitor shows bottom-up, in portrait mode same issue

**Comment by M0Rf30** [comment]
here some details:
P: /devices/pci0000:00/INT3432:00/i2c-5/i2c-SMO8500:00/iio:device0
N: iio:device0
E: DEVNAME=/dev/iio:device0
E: DEVPATH=/devices/pci0000:00/INT3432:00/i2c-5/i2c-SMO8500:00/iio:device0
E: DEVTYPE=iio_device
E: MAJOR=245
E: MINOR=0
E: SUBSYSTEM=iio
E: SYSTEMD_WANTS=iio-sensor-proxy.service
E: TAGS=:systemd:
E: USEC_INITIALIZED=10432122

**Comment by M0Rf30** [comment]
any news on this?

**Comment by hadess** [comment]
Your hardware uses the same accelerometer as the Onda v975w which needs a quirk. See `poll_orientation()` in `drv-iio-poll-accel.c`.

I don't know of an easy way to distinguish your tablet from this Onda one. Can you please attach the output of `dmidecode` to this bug?

**Comment by M0Rf30** [comment]
dmidecode out
https://gist.github.com/M0Rf30/c1c22ef00948307f49e0c1dfe6c0ad12

**Comment by hadess** [comment]
> you could extract the product name from dmi data and do a case switch, but this is only a humble suggestion for a person involved in such a project

Why do you think I asked for the dmidecode output? :)

**Comment by hadess** [comment]
One more question, do you have the DSDT for that device somewhere?
I'd need the `dsdt.dsl` generated from those instructions (just steps 1 and 2):
https://wiki.archlinux.org/index.php/DSDT#Recompiling_it_yourself

**Comment by M0Rf30** [comment]
I will provide you the dsdt as soon as possible. Maybe late in the afternoon

**Comment by M0Rf30** [comment]
https://gist.github.com/M0Rf30/005f91a7603311df19b6ef17da0cba17

**Comment by hadess** [comment]
OK, there's no _PLD so we'll have to use a quirk in udev for that device.

**Comment by hadess** [comment]
You can add a quirk for this in systemd/udev. See the "Accelerometer orientation" of the README.

**Comment by M0Rf30** [comment]
I will test the quirk and do a pull request in systemd 60-sensor.hwdb file. thanks man

**Comment by AlexGluck** [comment]
For asus tp300lj this not work, anyone can help me? 
cat /etc/udev/hwdb.d/61-sensor-local.hwdb
`#########################################
# AsusTek TP300LJ
#########################################
sensor:modalias:acpi:SMO8500*:dmi:*svn*ASUSTeK*:*pn*TP300LJ*
# ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 0
`

**Comment by hadess** [comment]
@AlexGluck wrong place to ask, the detection happens in systemd, so you should ask there.

But this is likely wrong:
```
ACCEL_MOUNT_MATRIX=0, -1, 0; -1, 0, 0; 0, 0, 0
```

The Z coordinate is just thrown away as the vector is all zeroes.

**Comment by AlexGluck** [comment]
I downgrade version of iio-proxy and all works fine. I add vector for Z coordinate, but nothing happen. I think fix for driver kxcj-9 broke correctly work. After that you say, what i need ask in systemd.

**Comment by M0Rf30** [comment]
it works with https://github.com/M0Rf30/scripts/blob/master/60-sensor.hwdb

**Comment by AlexGluck** [comment]
i don't understand why, but it not working. I try replace TP500LB to TP300LJ. If it help i can post dmidecode out.

**Comment by M0Rf30** [comment]
Are you using systemd-git? Accel_mount_matrix support is for latest commits of systemd and linux kernel>4.6

**Comment by AlexGluck** [comment]
No, i use fedora 25 with latest updates, systemd version now 231. Kernel 4.9.3. 
```
[alexgluck@gluck-laptop]$ lsiio
Device 001: i2c-SMO8500:00
Device 000: acpi-als
```
How i can check matrix uses for me?

**Comment by M0Rf30** [comment]
if you install latest systemd-git, you will find the accel_mount _matrix using the udevadm command listed in the README.md of iio-sensor-proxy. Execute the first step and I'll try to help you

**Comment by M0Rf30** [comment]
Done
https://github.com/systemd/systemd/pull/5111
