### ISSUE TITLE
XFCE4 Support

### ISSUE THREAD

**Issue by gevasiliou** [hadess/iio-sensor-proxy#95]
Hello There,
Nice job. This app really works in Ubuntu & Gnome 3.18. 
But i'm not capable to make it work properly under Debian Jessie + XFCE4 on the same machine.
iio-sensor-proxy is installed, accelermoter is detected, #monitor-sensor works fine , everything is there.
I tried suspend/restore , i also tried systemctl stop service and then start service but nothing worked.

I would appreciate if you had any ideas....

[gdbus log.txt](https://github.com/hadess/iio-sensor-proxy/files/346131/gdbus.log.txt)
[systemctl.txt](https://github.com/hadess/iio-sensor-proxy/files/346132/systemctl.txt)
[udevadmlog.txt](https://github.com/hadess/iio-sensor-proxy/files/346133/udevadmlog.txt)
[dmesg.txt](https://github.com/hadess/iio-sensor-proxy/files/346134/dmesg.txt)

**Comment by hadess** [comment]
XFCE will need to write code to read the data from the sensor service and do something with it. iio-sensor-proxy just reads the values and offers a unified API to access it.
