### ISSUE TITLE
Dell Inspiron 15 7000 issue.

### ISSUE THREAD

**Issue by amrit92** [hadess/iio-sensor-proxy#97]
I installed this script from the package manager in Manjaro Linux. No rotation seems to take place.

~> gdbus introspect --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy
Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name net.hadess.SensorProxy was not provided by any .service file

output of: G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy
** (process:3694): DEBUG: Could not find any supported sensors

**Comment by hadess** [comment]
This means that you don't have any supported sensors. Either the driver is missing from the kernel configuration, or there are no sensors in the device. Please check in the forums for your distribution or hardware provider, we cannot support devices without drivers.

(If you're lucky, it includes an Intel Integrated Sensor Hub, ask your distribution vendor about a backport)
