### ISSUE TITLE
Dell Inspiron 13 5000

### ISSUE THREAD

**Issue by pechols3** [hadess/iio-sensor-proxy#98]
Command "udevadm info --export-db" results in no lines that contain "iio:device0"  but several that contain  "SYSTEMD_WANTS=iio-sensor-proxy.service".  

G_MESSAGES_DEBUG=all /usr/sbin/iio-sensor-proxy returns "DEBUG: Could not find any supported sensors"  

Kernel is 4.4.0-36-generic

Suggestions sought

**Comment by hadess** [comment]
This means that you don't have any supported sensors. Either the driver is missing from the kernel configuration, or there are no sensors in the device. Please check in the forums for your distribution or hardware provider, we cannot support devices without drivers.

(If you're lucky, it includes an Intel Integrated Sensor Hub, ask your distribution vendor about a backport)
